global using MakeYourBusinessGreen.Application.Interfaces;
global using MakeYourBusinessGreen.Application.Models;
global using MakeYourBusinessGreen.Infastructure.Authentication;
global using MakeYourBusinessGreen.Infastructure.Persistence.Contexts;
global using MakeYourBusinessGreen.Infastructure.Persistence.Repositories;
